CURRENCIES = {
    "USD": { "id": 1, "sign": "$%"},
    "GBP": { "id": 2, "sign": "£%"},
    "EUR": { "id": 3, "sign": "%€"},
    "CHF": { "id": 4, "sign": "CHF %"},
    "RUB": { "id": 5, "sign": "% pуб."},
    "PLN": { "id": 6, "sign": "%zł"},
    "BRL": { "id": 7, "sign": "R$ %"},
    "JPY": { "id": 8, "sign": "¥ %"},
    "NOK": { "id": 9, "sign": "% kr"},
    "IDR": { "id": 10, "sign": "Rp %"},
    "MYR": { "id": 11, "sign": "RM%"},
    "PHP": { "id": 12, "sign": "P%"},
    "SGD": { "id": 13, "sign": "S$%"},
    "THB": { "id": 14, "sign": "฿%"},
    "VND": { "id": 15, "sign": "%₫"},
    "KRW": { "id": 16, "sign": "₩ %"},
    "TRY": { "id": 17, "sign": "% TL"},
    "UAH": { "id": 18, "sign": "%₴"},
    "MXN": { "id": 19, "sign": "Mex$ %"},
    "CAD": { "id": 20, "sign": "CDN$ %"},
    "AUD": { "id": 21, "sign": "A$ %"},
    "NZD": { "id": 22, "sign": "NZ$ %"},
    "CNY": { "id": 23, "sign": "¥ %"},
    "INR": { "id": 24, "sign": "₹ %"},
    "CLP": { "id": 25, "sign": "CLP$ %"},
    "PEN": { "id": 26, "sign": "S/.%"},
    "COP": { "id": 27, "sign": "COL$ %"},
    "ZAR": { "id": 28, "sign": "R %"},
    "HKD": { "id": 29, "sign": "HK$ %"},
    "TWD": { "id": 30, "sign": "NT$ %"},
    "SAR": { "id": 31, "sign": "% SR"},
    "AED": { "id": 32, "sign": "% AED"},
    "ARS": { "id": 34, "sign": "ARS$ %"},
    "ILS": { "id": 35, "sign": "₪%"},
    "KZT": { "id": 37, "sign": "%₸"},
    "KWD": { "id": 38, "sign": "% KD"},
    "QAR": { "id": 39, "sign": "% QR"},
    "CRC": { "id": 40, "sign": "₡%"},
    "UYU": { "id": 41, "sign": "$U%"},
}

def currency_string(num, currency_id):
    return CURRENCIES[currency_id]["sign"].replace("%", f"{num:.2f}")